import kaggle_benchmarks as kbench
from kaggle_benchmarks.prompting import ResponseParsingError
from pydantic import BaseModel, Field
import re


class MathAnswers(BaseModel):
    q11: str = Field(
        description="The answer for question 11. Use LaTeX format, e.g., \\frac{\\sqrt{a}}{b}."
    )
    q12: str = Field(
        description="The answer for question 12. Use LaTeX format, e.g., \\frac{a}{b}."
    )
    q13: str = Field(
        description="The answer for question 13. Use LaTeX format, e.g., \\sqrt{a}."
    )
    q14_1: str = Field(
        description="The answer for question 14, part (1). Use interval notation, e.g., (a, b]."
    )
    q14_2: str = Field(
        description="The answer for question 14, part (2). Use interval notation, e.g., (a, b]."
    )
    q15: str = Field(
        description="The answer for question 15, list the correct statement numbers (e.g., 2 3)."
    )


@kbench.task(name="MPT-Bench - 2026.3.22 - Part 2")
def solve_math_problems(llm) -> tuple[int, int]:
    prompt = r"""
Solve the following math problems. Provide your answers in a single JSON object matching the specified schema. For fill-in-the-blank questions requiring fractions or square roots, use LaTeX format (e.g., \\frac{a}{b}, \\sqrt{c}). For interval questions, use standard interval notation (e.g., [a, b) or (c, d]).

11. The eccentricity of the ellipse \(\frac{x^{2}}{9}+\frac{y^{2}}{6}=1\) is \(\underline{\hspace{6cm}}\).

12. Let the sequence \(\{a_{n}\}\) be an arithmetic progression with nonzero common difference, and suppose \(a_{1}+a_{10}=a_{9}\). Then
\frac{a_{1}+a_{2}+\ldots+a_{9}}{a_{10}}=\underline{\hspace{6cm}}.

13. Blue-and-white porcelain is a treasure of Chinese ceramic craftsmanship. The figure shows a floor-standing blue-and-white vase whose profile is a one-sheet hyperboloid; it can be regarded as the surface generated by rotating a branch of a hyperbola about its imaginary axis. If the minimal diameter of the vase’s circular cross-section is \(16\ \text{cm}\), the diameter of the upper mouth circle is \(20\ \text{cm}\), and the distance between the centers of the upper mouth circle and the minimal cross-section circle is \(12\ \text{cm}\), then the eccentricity of the corresponding hyperbola is \(\underline{\hspace{6cm}}\).

14. Let the function
f(x)=
\begin{cases}
-x+a, & x\le 1,\\[4pt]
-a(x-2)^2+1, & x>1.
\end{cases}
(1) If \(a=2\), the interval on which \(f(x)\) is increasing is \(\underline{\hspace{6cm}}\).
(2) If the range of \(f(x)\) is \((-\infty,+\infty)\), then the possible values of \(a\) are \(\underline{\hspace{6cm}}\).

15. Let the function \(f(x)=\sqrt{x^{3}-x}\). The following four statements are given:
① The function \(f(x)\) is an odd function;
② \(\forall k\in\mathbb{R}\) and \(k\neq0\), the equation in \(x\) \(f(x)-kx=0\) has exactly two distinct real roots;
③ Let \(P\) be an arbitrary point on the curve \(y=f(x)\), and \(A(-\frac{1}{2},0)\). Then \(|AP|\ge\frac{1}{2}\);
④ Let \(M(x_{1},y_{1})\) be a point on the curve \(y=f(x)\) and \(N(x_{2},y_{2})\) be a point on the curve \(y=-f(x)\). If \(|x_{1}+x_{2}|=1\), then \(|MN|\ge1\).
The numbers of all correct statements are \(\underline{\hspace{3cm}}\).
"""
    total_score = 30
    earned_score = 0
    try:
        response = llm.prompt(prompt, schema=MathAnswers)

        q11_correct = bool(
            re.search(
                r"\\frac\{\s*\\sqrt\{3\}\s*\}\{\s*3\s*\}", response.q11.replace(" ", "")
            )
        )
        kbench.assertions.assert_true(
            q11_correct,
            expectation="Question 11 answer should be \\frac{\\sqrt{3}}{3}.",
        )
        if q11_correct:
            earned_score += 6

        q12_correct = bool(
            re.search(r"\\frac\{\s*27\s*\}\{\s*8\s*\}", response.q12.replace(" ", ""))
        )
        kbench.assertions.assert_true(
            q12_correct, expectation="Question 12 answer should be \\frac{27}{8}."
        )
        if q12_correct:
            earned_score += 6

        q13_correct = bool(
            re.search(r"\\sqrt\{\s*5\s*\}", response.q13.replace(" ", ""))
        )
        kbench.assertions.assert_true(
            q13_correct, expectation="Question 13 answer should be \\sqrt{5}."
        )
        if q13_correct:
            earned_score += 6

        q14_1_correct = "(1,2]" in response.q14_1.replace(" ", "")
        kbench.assertions.assert_true(
            q14_1_correct, expectation="Question 14(1) answer should be (1, 2]."
        )
        q14_2_correct = "(0,2]" in response.q14_2.replace(" ", "")
        kbench.assertions.assert_true(
            q14_2_correct, expectation="Question 14(2) answer should be (0, 2]."
        )
        if q14_1_correct and q14_2_correct:
            earned_score += 6

        q15_correct = (
            "2" in response.q15
            and "3" in response.q15
            and "4" in response.q15
            and "1" not in response.q15
        )
        kbench.assertions.assert_true(
            q15_correct, expectation="Question 15 answer should be 2 3 4."
        )
        if q15_correct:
            earned_score += 6

    except ResponseParsingError as e:
        kbench.assertions.assert_fail(
            f"Failed to parse LLM response into MathAnswers schema. Error: {e.error}"
        )
        return 0, total_score
    return earned_score, total_score


solve_math_problems.run(kbench.llm)
