import kaggle_benchmarks as kbench
import textwrap


@kbench.task(name="MPT-Bench - 2026.3.22 - Part 2")
def solve_math_problems(llm) -> tuple[int, int]:
    prompt = textwrap.dedent(
        r"""
    Solve the following math problems. Show your work and provide a clear final answer for each question.

    11. The eccentricity of the ellipse \(\frac{x^{2}}{9}+\frac{y^{2}}{6}=1\) is \(\underline{\hspace{6cm}}\).

    12. Let the sequence \(\{a_{n}\}\) be an arithmetic progression with nonzero common difference, and suppose \(a_{1}+a_{10}=a_{9}\). Then
    \frac{a_{1}+a_{2}+\ldots+a_{9}}{a_{10}}=\underline{\hspace{6cm}}.

    13. Blue-and-white porcelain is a treasure of Chinese ceramic craftsmanship. The figure shows a floor-standing blue-and-white vase whose profile is a one-sheet hyperboloid; it can be regarded as the surface generated by rotating a branch of a hyperbola about its imaginary axis. If the minimal diameter of the vase’s circular cross-section is \(16\ \text{cm}\), the diameter of the upper mouth circle is \(20\ \text{cm}\), and the distance between the centers of the upper mouth circle and the minimal cross-section circle is \(12\ \text{cm}\), then the eccentricity of the corresponding hyperbola is \(\underline{\hspace{6cm}}\).

    14. Let the function
    f(x)=
    \begin{cases}
    -x+a, & x\le 1,\\[4pt]
    -a(x-2)^2+1, & x>1.
    \end{cases}
    (1) If \(a=2\), the interval on which \(f(x)\) is increasing is \(\underline{\hspace{6cm}}\).
    (2) If the range of \(f(x)\) is \((-\infty,+\infty)\), then the possible values of \(a\) are \(\underline{\hspace{6cm}}\).

    15. Let the function \(f(x)=\sqrt{x^{3}-x}\). The following four statements are given:
    ① The function \(f(x)\) is an odd function;
    ② \(\forall k\in\mathbb{R}\) and \(k\neq0\), the equation in \(x\) \(f(x)-kx=0\) has exactly two distinct real roots;
    ③ Let \(P\) be an arbitrary point on the curve \(y=f(x)\), and \(A(-\frac{1}{2},0)\). Then \(|AP|\ge\frac{1}{2}\);
    ④ Let \(M(x_{1},y_{1})\) be a point on the curve \(y=f(x)\) and \(N(x_{2},y_{2})\) be a point on the curve \(y=-f(x)\). If \(|x_{1}+x_{2}|=1\), then \(|MN|\ge1\).
    The numbers of all correct statements are \(\underline{\hspace{3cm}}\).
    """
    )

    response = llm.prompt(prompt)

    criteria = [
        r"The final answer for Question 11 is mathematically equivalent to \(\frac{\sqrt{3}}{3}\) or \(\frac{1}{\sqrt{3}}\).",
        r"The final answer for Question 12 is mathematically equivalent to \(\frac{27}{8}\) or 3.375.",
        r"The final answer for Question 13 is mathematically equivalent to \(\sqrt{5}\).",
        r"The final answer for Question 14 is two intervals: 14(1) is \((1, 2]\) and 14(2) is \((0, 2]\).",
        r"For Question 15, the correct statements identified must be exactly ②, ③, and ④ (or 2, 3, 4). Any other combination is incorrect.",
    ]

    assessment = kbench.assertions.assess_response_with_judge(
        criteria=criteria, response_text=response, judge_llm=kbench.judge_llm
    )

    if assessment is None:
        kbench.assertions.assert_fail(
            expectation="Judge LLM failed to return a valid assessment."
        )
        return 0, 30

    earned_score = 0
    passed_statuses = []

    for result in assessment.results:
        passed_statuses.append(result.passed)
        if result.passed:
            earned_score += 6
        kbench.assertions.assert_true(
            result.passed,
            expectation=f"Criterion failed: '{result.criterion}'. Reason: {result.reason}",
        )

    return earned_score, 30


solve_math_problems.run(kbench.llm)
